version: '3.8'

services:
  dz-portainer:
    image: dz-server/portainer-ce:1.0.0
    container_name: dz-portainer
    restart: always
    privileged: false
    environment: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - public:/public
    ports:
      - ${HttpPort}:9000
      - ${HttpsPort}:9443

volumes:
  data:
  public:
