version: '3.8'

services:
  dz-nginx-proxy:
    image: dz-server/nginx-proxy:1.0.0
    container_name: dz-nginx-proxy
    restart: always
    privileged: false
    environment: {}
    volumes:
      - static:/usr/share/nginx/html
      - conf:/etc/nginx/
      - log:/var/log/nginx
    ports:
      - 80:80
      # - ${HttpsPort}:443


volumes:
  static:
  conf:
  log:


